[project]
name = "fortuned"
version = "1.0.2"
description = "A fortune teller that doesn't really tell you your fortune."

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
fortuned = "fortuned.app"

[project.scripts]
fortuned = "fortuned:app"
