[project]
name = "fortuned"
version = "1.0.0"
description = "A fortune teller that doesn't really tell you your fortune."
dependencies = [
    "flask",
    "flask-babel",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"